<?php

use Illuminate\Database\Seeder;

class CustomersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('customers')->insert(['id' => 1, 'name' => 'Alan D Rosenburg Cpa Pc', 'vat' => '123456789', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 2, 'name' => 'Cap Gemini America', 'vat' => '123456790', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 3, 'name' => 'Elliott, John W Esq', 'vat' => '123456791', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 4, 'name' => 'Mcmahan, Ben L', 'vat' => '123456792', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 5, 'name' => 'Champagne Room', 'vat' => '123456793', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "5396 Forth Street", "city": "Greets Green and Lyng Ward", "province": "West Midlands", "postal_code": "B70 9DT", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01547-429341", "phone2": "01290-367248", "email": "info@champagneroom.co.uk", "web": "http://www.champagneroom.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 6, 'name' => 'Thompson, Michael C Esq', 'vat' => '123456794', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "9472 Lind St", "city": "Desborough", "province": "Northamptonshire", "postal_code": "NN14 2GH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01969-886290", "phone2": "01545-817375", "email": "info@thompsonmichaelcesq.co.uk", "web": "http://www.thompsonmichaelcesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 7, 'name' => 'Wrangle Hill Auto Auct & Slvg', 'vat' => '123456795', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "7457 Cowl St #70", "city": "Bargate Ward", "province": "Southampton", "postal_code": "SO14 3TY", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01865-582516", "phone2": "01362-620532", "email": "info@wranglehillautoauctslvg.co.uk", "web": "http://www.wranglehillautoauctslvg.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 8, 'name' => 'In Communications Inc', 'vat' => '123456796', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "20 Gloucester Pl #96", "city": "Chirton Ward", "province": "Tyne & Wear", "postal_code": "NE29 7AD", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01746-394243", "phone2": "01590-982428", "email": "info@incommunicationsinc.co.uk", "web": "http://www.incommunicationsinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 9, 'name' => 'Bizerba Usa Inc', 'vat' => '123456797', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "929 Augustine St", "city": "Staple Hill Ward", "province": "South Gloucestershire", "postal_code": "BS16 4LL", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01907-538509", "phone2": "01340-713951", "email": "info@bizerbausainc.co.uk", "web": "http://www.bizerbausainc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 10, 'name' => 'Max Video', 'vat' => '123456798', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "45 Bradfield St #166", "city": "Parwich", "province": "Derbyshire", "postal_code": "DE6 1QN", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01903-649460", "phone2": "01933-512513", "email": "info@maxvideo.co.uk", "web": "http://www.maxvideo.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 11, 'name' => 'K & R Associates Inc', 'vat' => '123456799', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "620 Northampton St", "city": "Wilmington", "province": "Kent", "postal_code": "DA2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01630-202053", "phone2": "01687-879391", "email": "info@krassociatesinc.co.uk", "web": "http://www.krassociatesinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 12, 'name' => 'Cain, John M Esq', 'vat' => '123456800', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "5 Hygeia St", "city": "Loundsley Green Ward", "province": "Derbyshire", "postal_code": "S40 4LY", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01276-816806", "phone2": "01517-624517", "email": "info@cainjohnmesq.co.uk", "web": "http://www.cainjohnmesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 13, 'name' => 'Sound Vision Corp', 'vat' => '123456801', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "2150 Morley St", "city": "Dee Ward", "province": "Dumfries and Galloway", "postal_code": "DG8 7DE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01625-932209", "phone2": "01642-322954", "email": "info@soundvisioncorp.co.uk", "web": "http://www.soundvisioncorp.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 14, 'name' => 'Rowley/hansell Petetin', 'vat' => '123456802', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "24 Bolton St", "city": "Broxburn, Uphall and Winchburg", "province": "West Lothian", "postal_code": "EH52 5TL", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01874-856950", "phone2": "01342-793603", "email": "info@rowleyhansellpetetin.co.uk", "web": "http://www.rowleyhansellpetetin.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 15, 'name' => 'Industrial Engineering Assocs', 'vat' => '123456803', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "4 Forrest St", "city": "Weston-Super-Mare", "province": "North Somerset", "postal_code": "BS23 3HG", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01976-755279", "phone2": "01956-535511", "email": "info@industrialengineeringassocs.co.uk", "web": "http://www.industrialengineeringassocs.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 16, 'name' => 'Weiss Spirt & Guyer', 'vat' => '123456804', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "89 Noon St", "city": "Carbrooke", "province": "Norfolk", "postal_code": "IP25 6JQ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01967-580851", "phone2": "01672-496478", "email": "info@weissspirtguyer.co.uk", "web": "http://www.weissspirtguyer.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 17, 'name' => 'Crowan, Kenneth W Esq', 'vat' => '123456805', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "99 Guthrie St", "city": "New Milton", "province": "Hampshire", "postal_code": "BH25 5DF", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01326-532337", "phone2": "01666-638176", "email": "info@crowankennethwesq.co.uk", "web": "http://www.crowankennethwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 18, 'name' => 'Rittenhouse Motor Co', 'vat' => '123456806', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "7 Richmond St", "city": "Parkham", "province": "Devon", "postal_code": "EX39 5DJ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01253-528327", "phone2": "01241-964675", "email": "info@rittenhousemotorco.co.uk", "web": "http://www.rittenhousemotorco.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 19, 'name' => 'Modern Plastics Corp', 'vat' => '123456807', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "9165 Primrose St", "city": "Darnall Ward", "province": "Yorkshire, South", "postal_code": "S4 7WN", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01719-831436", "phone2": "01207-428520", "email": "info@modernplasticscorp.co.uk", "web": "http://www.modernplasticscorp.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 20, 'name' => 'Galloway Electric Co Inc', 'vat' => '123456808', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "9 Pengwern St", "city": "Marldon", "province": "Devon", "postal_code": "TQ3 1SA", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01578-287816", "phone2": "01939-815208", "email": "info@gallowayelectriccoinc.co.uk", "web": "http://www.gallowayelectriccoinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 21, 'name' => 'Niagara Custombuilt Mfg Co', 'vat' => '123456809', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "4410 Tarlton St", "city": "Prestatyn Community", "province": "Denbighshire", "postal_code": "LL19 9EG", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01842-767201", "phone2": "01859-648598", "email": "info@niagaracustombuiltmfgco.co.uk", "web": "http://www.niagaracustombuiltmfgco.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 22, 'name' => 'Practical Periphrals', 'vat' => '123456810', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "6949 Bourne St", "city": "Lye and Stourbridge North Ward", "province": "West Midlands", "postal_code": "DY5 2QP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01552-709248", "phone2": "01743-139456", "email": "info@practicalperiphrals.co.uk", "web": "http://www.practicalperiphrals.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 23, 'name' => 'Curtin, Patricia M Esq', 'vat' => '123456811', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "148 Rembrandt St", "city": "Warlingham", "province": "Surrey", "postal_code": "CR6 9SW", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01677-684257", "phone2": "01583-287367", "email": "info@curtinpatriciamesq.co.uk", "web": "http://www.curtinpatriciamesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 24, 'name' => 'Wilhelm, James E Jr', 'vat' => '123456812', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "2200 Nelson St #58", "city": "Newport", "province": "Isle of Wight", "postal_code": "PO30 5AL", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01217-342071", "phone2": "01280-786847", "email": "info@wilhelmjamesejr.co.uk", "web": "http://www.wilhelmjamesejr.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 25, 'name' => 'Smart Signs', 'vat' => '123456813', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "61 Rossett St", "city": "Chichester", "province": "West Sussex", "postal_code": "PO19 1RH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01473-229124", "phone2": "01848-116775", "email": "info@smartsigns.co.uk", "web": "http://www.smartsigns.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 26, 'name' => 'Arctic Star Distributing Inc', 'vat' => '123456814', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "41 Canning St", "city": "Steornabhagh a Deas Ward", "province": "Western Isles", "postal_code": "HS1 2PZ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01230-623547", "phone2": "01604-718601", "email": "info@arcticstardistributinginc.co.uk", "web": "http://www.arcticstardistributinginc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 27, 'name' => 'Lensbower, Gregory L Esq', 'vat' => '123456815', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "8289 Cadogan St", "city": "South Ward", "province": "North Eart Lincolnshire", "postal_code": "DN33 1AU", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01781-827317", "phone2": "01509-121140", "email": "info@lensbowergregorylesq.co.uk", "web": "http://www.lensbowergregorylesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 28, 'name' => 'Portal Metal Products', 'vat' => '123456816', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "211 Hobart St", "city": "Newquay", "province": "Cornwall", "postal_code": "TR7 1LS", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01866-248660", "phone2": "01315-284286", "email": "info@portalmetalproducts.co.uk", "web": "http://www.portalmetalproducts.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 29, 'name' => 'Lynema, Cliff Cpa', 'vat' => '123456817', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "114 Falkland St #8845", "city": "Brimpton", "province": "Berkshire", "postal_code": "RG7 4RF", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01541-802635", "phone2": "01926-108010", "email": "info@lynemacliffcpa.co.uk", "web": "http://www.lynemacliffcpa.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 30, 'name' => 'J C S Machinery', 'vat' => '123456818', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "1 Birkett St", "city": "Shard End Ward", "province": "West Midlands", "postal_code": "B33 0NH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01857-864722", "phone2": "01307-667811", "email": "info@jcsmachinery.co.uk", "web": "http://www.jcsmachinery.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 31, 'name' => 'Berick, Joseph G Esq', 'vat' => '123456819', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "5147 Blackstone St", "city": "Letchworth South West Ward", "province": "Hertfordshire", "postal_code": "SG6 3LE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01243-678286", "phone2": "01292-297245", "email": "info@berickjosephgesq.co.uk", "web": "http://www.berickjosephgesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 32, 'name' => 'Jackson & Heit Machine Co Inc', 'vat' => '123456820', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "7 Shenstone St", "city": "Longhill Ward", "province": "Yorkshire, East (North Humbers", "postal_code": "HU8 9PZ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01400-269033", "phone2": "01366-210656", "email": "info@jacksonheitmachinecoinc.co.uk", "web": "http://www.jacksonheitmachinecoinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 33, 'name' => 'Bridgeway Plan For Health', 'vat' => '123456821', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "129 Alexander Pope St", "city": "Franche Ward", "province": "Hereford and Worcester", "postal_code": "DY11 9BW", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01702-725589", "phone2": "01421-132652", "email": "info@bridgewayplanforhealth.co.uk", "web": "http://www.bridgewayplanforhealth.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 34, 'name' => 'Wa Inst For Plcy Studies', 'vat' => '123456822', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "2 Birchfield Rd", "city": "Whittington", "province": "Shropshire", "postal_code": "SY11 4PH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01462-648669", "phone2": "01405-648623", "email": "info@wainstforplcystudies.co.uk", "web": "http://www.wainstforplcystudies.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 35, 'name' => 'Wmgl 101.7 Fm', 'vat' => '123456823', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "7523 Kempton Rd", "city": "Cockerton West Ward", "province": "Darlington", "postal_code": "DL3 0JF", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01235-647932", "phone2": "01809-443217", "email": "info@wmglfm.co.uk", "web": "http://www.wmglfm.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 36, 'name' => 'Hughlett, Henry T Jr', 'vat' => '123456824', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "6305 Elstow St", "city": "Castle Ward", "province": "West Sussex", "postal_code": "BN12 6PR", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01662-114247", "phone2": "01351-868965", "email": "info@hughletthenrytjr.co.uk", "web": "http://www.hughletthenrytjr.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 37, 'name' => 'Penrose Place Pharmacy Inc', 'vat' => '123456825', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "218 Greenbank Drive", "city": "Devizes", "province": "Wiltshire", "postal_code": "SN10 3DU", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01407-866759", "phone2": "01640-661191", "email": "info@penroseplacepharmacyinc.co.uk", "web": "http://www.penroseplacepharmacyinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 38, 'name' => 'Novak, Alan Paul Esq', 'vat' => '123456826', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "8921 Forge St", "city": "Colnbrook with Poyle", "province": "Buckinghamshire", "postal_code": "SL3 0PY", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01822-563044", "phone2": "01765-519419", "email": "info@novakalanpaulesq.co.uk", "web": "http://www.novakalanpaulesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 39, 'name' => 'B & S Tool And Cutter Svc Inc', 'vat' => '123456827', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "3060 St Ambrose Grove #261", "city": "Aldridge Central and South War", "province": "West Midlands", "postal_code": "WS9 8UR", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01327-770774", "phone2": "01286-258121", "email": "info@bstoolandcuttersvcinc.co.uk", "web": "http://www.bstoolandcuttersvcinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 40, 'name' => 'Berry, John M Esq', 'vat' => '123456828', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "8388 Bessemer St #5", "city": "East Putney Ward", "province": "Greater London", "postal_code": "SW15 2RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01483-418969", "phone2": "01818-980469", "email": "info@berryjohnmesq.co.uk", "web": "http://www.berryjohnmesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 41, 'name' => 'Alden, Michael H Esq', 'vat' => '123456829', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "87 Pownall Sq", "city": "Sawston", "province": "Cambridgeshire", "postal_code": "CB22 3BB", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01709-854691", "phone2": "01572-193368", "email": "info@aldenmichaelhesq.co.uk", "web": "http://www.aldenmichaelhesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 42, 'name' => 'Ernest E Heuer & Company Pc', 'vat' => '123456830', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "39 Wye St", "city": "Wakefield North Ward", "province": "West Yorkshire", "postal_code": "WF1 1DR", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01609-882184", "phone2": "01295-331807", "email": "info@ernesteheuercompanypc.co.uk", "web": "http://www.ernesteheuercompanypc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 43, 'name' => 'Frankel, Stephen', 'vat' => '123456831', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "2732 Bostock St #1", "city": "St. Enoder", "province": "Cornwall", "postal_code": "TR9 6NJ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01693-310794", "phone2": "01512-975244", "email": "info@frankelstephen.co.uk", "web": "http://www.frankelstephen.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 44, 'name' => 'Guynes Design Inc', 'vat' => '123456832', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "5562 Fairfield St #847", "city": "Ryde", "province": "Isle of Wight", "postal_code": "PO33 1HH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01891-702579", "phone2": "01333-972244", "email": "info@guynesdesigninc.co.uk", "web": "http://www.guynesdesigninc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 45, 'name' => 'General Appraisal Co', 'vat' => '123456833', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "37 Meadow St", "city": "Laindon Park Ward", "province": "Essex", "postal_code": "SS15 6LE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01850-347846", "phone2": "01222-164469", "email": "info@generalappraisalco.co.uk", "web": "http://www.generalappraisalco.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 46, 'name' => 'Sheraton Inn Ocean Front', 'vat' => '123456834', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "3 Nevison St", "city": "Lymington and Pennington", "province": "Hampshire", "postal_code": "SO41 1DL", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01420-307327", "phone2": "01245-559333", "email": "info@sheratoninnoceanfront.co.uk", "web": "http://www.sheratoninnoceanfront.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 47, 'name' => 'Cooper Myers Y Co', 'vat' => '123456835', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "5662 William Moult St", "city": "Aylesbury", "province": "Buckinghamshire", "postal_code": "HP21 8PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01567-296442", "phone2": "01493-245349", "email": "info@coopermyersyco.co.uk", "web": "http://www.coopermyersyco.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 48, 'name' => 'Cash 4 Checks', 'vat' => '123456836', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "3 North View #35", "city": "Burmantofts and Richmond Hill ", "province": "West Yorkshire", "postal_code": "LS9 7JH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01607-269930", "phone2": "01334-807355", "email": "info@cashchecks.co.uk", "web": "http://www.cashchecks.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 49, 'name' => 'Charlotte Chamber', 'vat' => '123456837', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "135 Opie St", "city": "Howard Town Ward", "province": "Derbyshire", "postal_code": "SK13 8BB", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01386-981141", "phone2": "01823-517315", "email": "info@charlottechamber.co.uk", "web": "http://www.charlottechamber.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 50, 'name' => 'Kisc 98 Kiss Fm', 'vat' => '123456838', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "1 Askew St", "city": "Farnham", "province": "Surrey", "postal_code": "GU9 9AS", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01260-641258", "phone2": "01415-364461", "email": "info@kisckissfm.co.uk", "web": "http://www.kisckissfm.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 51, 'name' => 'Schwartzbard, Gail L Esq', 'vat' => '123456839', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "4 Burnall St", "city": "Beeston West Ward", "province": "Nottinghamshire", "postal_code": "NG9 1AE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01543-198690", "phone2": "01231-806535", "email": "info@schwartzbardgaillesq.co.uk", "web": "http://www.schwartzbardgaillesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 52, 'name' => 'Marketing Horizons Inc', 'vat' => '123456840', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "95 Denton St", "city": "Wollaton West Ward", "province": "Nottinghamshire", "postal_code": "NG8 2NB", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01355-500797", "phone2": "01987-728730", "email": "info@marketinghorizonsinc.co.uk", "web": "http://www.marketinghorizonsinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 53, 'name' => 'Brady, Brad J Esq', 'vat' => '123456841', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "5 Chadwick St #7", "city": "Llangeler Community", "province": "Ceredigion", "postal_code": "SA44 5HF", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01252-621329", "phone2": "01442-700486", "email": "info@bradybradjesq.co.uk", "web": "http://www.bradybradjesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 54, 'name' => 'Welders Supply', 'vat' => '123456842', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "67 Micawber St", "city": "Brockley Ward", "province": "Greater London", "postal_code": "SE14 6RQ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01712-135466", "phone2": "01523-775781", "email": "info@welderssupply.co.uk", "web": "http://www.welderssupply.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 55, 'name' => 'Bomarko Inc', 'vat' => '123456843', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "43 Williamson St #7995", "city": "Meads Ward", "province": "East Sussex", "postal_code": "BN20 7HB", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01469-300335", "phone2": "01789-132579", "email": "info@bomarkoinc.co.uk", "web": "http://www.bomarkoinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 56, 'name' => 'Benitez, Brigida Esq', 'vat' => '123456844', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "5 Howe St", "city": "Broxburn, Uphall and Winchburg", "province": "West Lothian", "postal_code": "EH52 6NF", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01428-343825", "phone2": "01814-878359", "email": "info@benitezbrigidaesq.co.uk", "web": "http://www.benitezbrigidaesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 57, 'name' => 'Kennedy Scales Inc', 'vat' => '123456845', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "7 Cheapside #9", "city": "St. Ive", "province": "Cornwall", "postal_code": "PL14 5PA", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01770-129032", "phone2": "01639-518104", "email": "info@kennedyscalesinc.co.uk", "web": "http://www.kennedyscalesinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 58, 'name' => 'Barajas & Bustamante Archl', 'vat' => '123456846', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "85 Bridgewater St", "city": "Shard End Ward", "province": "West Midlands", "postal_code": "B34 7BP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01689-253476", "phone2": "01376-851958", "email": "info@barajasbustamantearchl.co.uk", "web": "http://www.barajasbustamantearchl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 59, 'name' => 'Brewster Wallcoverings Co', 'vat' => '123456847', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "763 Parkfield Rd", "city": "Norton Canes", "province": "Staffordshire", "postal_code": "WS11 9RH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01823-383806", "phone2": "01245-146126", "email": "info@brewsterwallcoveringsco.co.uk", "web": "http://www.brewsterwallcoveringsco.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 60, 'name' => 'Bohs Well Drilling Inc', 'vat' => '123456848', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "662 Grove Park", "city": "Bulwell Ward", "province": "Nottinghamshire", "postal_code": "NG6 8RG", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-634521", "phone2": "01702-946496", "email": "info@bohswelldrillinginc.co.uk", "web": "http://www.bohswelldrillinginc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 61, 'name' => 'Gavin, Lee W Esq', 'vat' => '123456849', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "5410 Lawton St", "city": "Treorchy Community", "province": "Rhondda Cynon Taff", "postal_code": "CF42 6PL", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01383-647035", "phone2": "01351-200904", "email": "info@gavinleewesq.co.uk", "web": "http://www.gavinleewesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 62, 'name' => 'Reid, Carleton B Esq', 'vat' => '123456850', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "3 August Rd", "city": "Maybury and Sheerwater Ward", "province": "Surrey", "postal_code": "GU21 5QL", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01670-813697", "phone2": "01903-424890", "email": "info@reidcarletonbesq.co.uk", "web": "http://www.reidcarletonbesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 63, 'name' => 'Canterbury, Christopher C', 'vat' => '123456851', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "476 Starkie St", "city": "Westgate Ward", "province": "Gloucestershire", "postal_code": "GL1 1QW", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01472-324699", "phone2": "01841-979075", "email": "info@canterburychristopherc.co.uk", "web": "http://www.canterburychristopherc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 64, 'name' => 'Omni Mandalay', 'vat' => '123456852', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "6448 Tillard St", "city": "Conisbrough and Denaby Ward", "province": "South Yorkshire", "postal_code": "DN12 4JF", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01412-528394", "phone2": "01580-134516", "email": "info@omnimandalay.co.uk", "web": "http://www.omnimandalay.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 65, 'name' => 'Lba Savings Bank', 'vat' => '123456853', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "3055 Creswick St", "city": "Newbold and Brownsover Ward", "province": "Warwickshire", "postal_code": "CV21 1LN", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01670-234959", "phone2": "01488-872531", "email": "info@lbasavingsbank.co.uk", "web": "http://www.lbasavingsbank.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 66, 'name' => 'Lutz, Christopher T Esq', 'vat' => '123456854', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "7 Jolliffe St", "city": "Middlewich", "province": "Cheshire", "postal_code": "CW10 9GB", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01947-566661", "phone2": "01481-295251", "email": "info@lutzchristophertesq.co.uk", "web": "http://www.lutzchristophertesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 67, 'name' => 'Association Of Art Museum Dir', 'vat' => '123456855', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "1175 Greig St", "city": "St. Marys Ward", "province": "Greater Manchester", "postal_code": "M25 0ZN", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01532-497454", "phone2": "01705-208145", "email": "info@associationofartmuseumdir.co.uk", "web": "http://www.associationofartmuseumdir.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 68, 'name' => 'L & L Sales Co Inc', 'vat' => '123456856', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "636 Portland Place", "city": "Gresham Ward", "province": "Middlesbrough", "postal_code": "TS1 4RG", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01743-977277", "phone2": "01704-986828", "email": "info@llsalescoinc.co.uk", "web": "http://www.llsalescoinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 69, 'name' => 'Cavuto, John A', 'vat' => '123456857', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "41 Benedict St", "city": "Aldborough Ward", "province": "Greater London", "postal_code": "IG2 7QG", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01599-245408", "phone2": "01695-305111", "email": "info@cavutojohna.co.uk", "web": "http://www.cavutojohna.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 70, 'name' => 'Pacific Coast Packaging', 'vat' => '123456858', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "62 Margaret St", "city": "Royal Hospital Ward", "province": "Greater London", "postal_code": "SW3 4ND", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01345-400452", "phone2": "01866-845669", "email": "info@pacificcoastpackaging.co.uk", "web": "http://www.pacificcoastpackaging.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 71, 'name' => 'Storm Eye Institute', 'vat' => '123456859', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "5152 Sophia St", "city": "Woodstock Ward", "province": "South Gloucestershire", "postal_code": "BS15 8DS", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01655-519837", "phone2": "01783-446052", "email": "info@stormeyeinstitute.co.uk", "web": "http://www.stormeyeinstitute.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 72, 'name' => 'Automation Engrg & Mfg Inc', 'vat' => '123456860', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "1 Back Canning St", "city": "Dunblane and Bridge of Allan W", "province": "Stirling", "postal_code": "FK9 4LD", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01837-530939", "phone2": "01752-386691", "email": "info@automationengrgmfginc.co.uk", "web": "http://www.automationengrgmfginc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 73, 'name' => 'Packaging Corp Of America', 'vat' => '123456861', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "9 Gradwell St", "city": "Kempshott Ward", "province": "Hampshire", "postal_code": "RG22 5HA", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01262-808399", "phone2": "01411-169215", "email": "info@packagingcorpofamerica.co.uk", "web": "http://www.packagingcorpofamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 74, 'name' => 'Goe, Douglas E Esq', 'vat' => '123456862', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "9205 Upper Hill St", "city": "City and Hunslet Ward", "province": "West Yorkshire", "postal_code": "LS1 5QE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01350-332706", "phone2": "01374-255198", "email": "info@goedouglaseesq.co.uk", "web": "http://www.goedouglaseesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 75, 'name' => 'Burgess Steel Products Corp', 'vat' => '123456863', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "9 Horatio St", "city": "Ruckinge", "province": "Kent", "postal_code": "TN26 2PN", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01686-306597", "phone2": "01970-890023", "email": "info@burgesssteelproductscorp.co.uk", "web": "http://www.burgesssteelproductscorp.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 76, 'name' => 'Tipton & Hurst', 'vat' => '123456864', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "61 Miriam St", "city": "Abbey Road Ward", "province": "Greater London", "postal_code": "NW8 9BD", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01537-356648", "phone2": "01703-435212", "email": "info@tiptonhurst.co.uk", "web": "http://www.tiptonhurst.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 77, 'name' => 'A O Hardee & Son Inc', 'vat' => '123456865', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "67 Pulford St", "city": "Prittlewell Ward", "province": "Essex", "postal_code": "SS2 6NL", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01388-416867", "phone2": "01345-625433", "email": "info@aohardeesoninc.co.uk", "web": "http://www.aohardeesoninc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 78, 'name' => 'Jonson, Geo D Esq', 'vat' => '123456866', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "821 Pembroke Place", "city": "Kirkby Stephen", "province": "Cumbria", "postal_code": "CA17 4RZ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01589-654152", "phone2": "01586-387018", "email": "info@jonsongeodesq.co.uk", "web": "http://www.jonsongeodesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 79, 'name' => 'Dale Yoder Clu Life Hlth & Bus', 'vat' => '123456867', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "3 Alder St", "city": "Eaton Park Ward", "province": "Stoke-on-Trent", "postal_code": "ST2 9AW", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01780-704167", "phone2": "01268-233798", "email": "info@daleyoderclulifehlthbus.co.uk", "web": "http://www.daleyoderclulifehlthbus.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 80, 'name' => 'Council Of Cmnty Blood Ctrs', 'vat' => '123456868', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "80 Morecambe St", "city": "Bishop Auckland", "province": "County Durham", "postal_code": "DL14 6NG", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01355-192668", "phone2": "01340-622388", "email": "info@councilofcmntybloodctrs.co.uk", "web": "http://www.councilofcmntybloodctrs.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 81, 'name' => 'Tremont, Michael A Esq', 'vat' => '123456869', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "7866 Renshaw St #283", "city": "Falmouth", "province": "Cornwall", "postal_code": "TR11 4QQ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01823-526645", "phone2": "01368-456268", "email": "info@tremontmichaelaesq.co.uk", "web": "http://www.tremontmichaelaesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 82, 'name' => 'Trautman, Eileen Esq', 'vat' => '123456870', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "658 Lake St", "city": "Malmesbury", "province": "Wiltshire", "postal_code": "SN16 0XZ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01777-469402", "phone2": "01631-454193", "email": "info@trautmaneileenesq.co.uk", "web": "http://www.trautmaneileenesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 83, 'name' => 'Office Service Co', 'vat' => '123456871', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "5382 Redfern St", "city": "West End Ward", "province": "Greater London", "postal_code": "W1J 0QH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01961-642757", "phone2": "01728-150282", "email": "info@officeserviceco.co.uk", "web": "http://www.officeserviceco.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 84, 'name' => 'Alphabetland Pre School Center', 'vat' => '123456872', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "45 Bidder St #38", "city": "Town Ward", "province": "Greater London", "postal_code": "EN1 3HT", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01367-136951", "phone2": "01322-715065", "email": "info@alphabetlandpreschoolcenter.co.uk", "web": "http://www.alphabetlandpreschoolcenter.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 85, 'name' => 'Shamrock Food Service', 'vat' => '123456873', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "6766 Britton St #379", "city": "Crompton Ward", "province": "Greater Manchester", "postal_code": "BL1 3EX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-749219", "phone2": "01308-356704", "email": "info@shamrockfoodservice.co.uk", "web": "http://www.shamrockfoodservice.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 86, 'name' => 'Central Hrdwr & Elec Corp', 'vat' => '123456874', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "7 Lear Rd", "city": "Stroud", "province": "Hampshire", "postal_code": "GU32 3PQ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01779-720349", "phone2": "01961-802899", "email": "info@centralhrdwreleccorp.co.uk", "web": "http://www.centralhrdwreleccorp.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 87, 'name' => 'Matt Parrott & Sons Co', 'vat' => '123456875', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "2577 Toxteth St #5", "city": "Overton Ward", "province": "Lancashire", "postal_code": "BB6 7UN", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01527-579687", "phone2": "01439-184366", "email": "info@mattparrottsonsco.co.uk", "web": "http://www.mattparrottsonsco.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 88, 'name' => 'Tiny Tots Originals Div', 'vat' => '123456876', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "761 Cockerell St #1", "city": "Midway Ward", "province": "Derbyshire", "postal_code": "DE11 0HE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01927-790069", "phone2": "01440-276155", "email": "info@tinytotsoriginalsdiv.co.uk", "web": "http://www.tinytotsoriginalsdiv.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 89, 'name' => 'Lovitch, Alan F', 'vat' => '123456877', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "9 Cypress St", "city": "Washington East Ward", "province": "Tyne and Wear", "postal_code": "NE38 9AQ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01753-784273", "phone2": "01496-526674", "email": "info@lovitchalanf.co.uk", "web": "http://www.lovitchalanf.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 90, 'name' => 'Wise Industries', 'vat' => '123456878', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "6 Romilly St", "city": "Walkergate Ward", "province": "Tyne and Wear", "postal_code": "NE6 4YH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01312-233253", "phone2": "01342-706893", "email": "info@wiseindustries.co.uk", "web": "http://www.wiseindustries.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 91, 'name' => 'East County Process', 'vat' => '123456879', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "51 St Anne St #12", "city": "Stratfield Mortimer", "province": "Berkshire", "postal_code": "RG7 3RA", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01241-273991", "phone2": "01381-836777", "email": "info@eastcountyprocess.co.uk", "web": "http://www.eastcountyprocess.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 92, 'name' => 'Agopgee Enterprises Inc', 'vat' => '123456880', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "823 Idris St", "city": "Selston", "province": "Nottinghamshire", "postal_code": "NG16 5LG", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01898-134749", "phone2": "01266-671305", "email": "info@agopgeeenterprisesinc.co.uk", "web": "http://www.agopgeeenterprisesinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 93, 'name' => 'L Winik & Associates Inc', 'vat' => '123456881', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "8764 Nickleby St #877", "city": "Govan Ward", "province": "Glasgow City", "postal_code": "G51 1BQ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01478-110943", "phone2": "01937-120539", "email": "info@lwinikassociatesinc.co.uk", "web": "http://www.lwinikassociatesinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 94, 'name' => 'Rosati, Marc D Esq', 'vat' => '123456882', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "5344 Bengel St #5", "city": "Millwall Ward", "province": "Greater London", "postal_code": "E14 5DR", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01402-733903", "phone2": "01440-164945", "email": "info@rosatimarcdesq.co.uk", "web": "http://www.rosatimarcdesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 95, 'name' => 'Rust Evader Corp', 'vat' => '123456883', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "8880 Great Howard St #7750", "city": "Sefton", "province": "Merseyside", "postal_code": "L29 7WD", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01358-446391", "phone2": "01414-780251", "email": "info@rustevadercorp.co.uk", "web": "http://www.rustevadercorp.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 96, 'name' => 'Budget Annex', 'vat' => '123456884', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "9 Oakleigh", "city": "Lancing", "province": "West Sussex", "postal_code": "BN15 9BN", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01448-211489", "phone2": "01929-400879", "email": "info@budgetannex.co.uk", "web": "http://www.budgetannex.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 97, 'name' => 'Kiqo Pure Gold Oldies 104 Fm', 'vat' => '123456885', 'type' => 'Customer', 'status' => 'Active', 'address_info' => '{"address": "83 Denbigh St Bootle", "city": "St. Gluvias", "province": "Cornwall", "postal_code": "TR3 7AZ", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01462-474800", "phone2": "01650-129106", "email": "info@kiqopuregoldoldiesfm.co.uk", "web": "http://www.kiqopuregoldoldiesfm.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 98, 'name' => 'Segall Majestic Inc', 'vat' => '123456886', 'type' => 'Prospect', 'status' => 'Not Active', 'address_info' => '{"address": "30 Aughton St", "city": "Hilton", "province": "Aberdeenshire", "postal_code": "AB24 2RR", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01240-600327", "phone2": "01408-918612", "email": "info@segallmajesticinc.co.uk", "web": "http://www.segallmajesticinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 99, 'name' => 'Taos Valley Resort Assn', 'vat' => '123456887', 'type' => 'Prospect', 'status' => 'Active', 'address_info' => '{"address": "260 Saxon St", "city": "Brooklands Ward", "province": "Greater Manchester", "postal_code": "M33 4BP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01537-525550", "phone2": "01204-471598", "email": "info@taosvalleyresortassn.co.uk", "web": "http://www.taosvalleyresortassn.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
        DB::table('customers')->insert(['id' => 100, 'name' => 'Exhibit Crafts Inc', 'vat' => '123456888', 'type' => 'Customer', 'status' => 'Not Active', 'address_info' => '{"address": "3 Pyramid St", "city": "Eccleston Ward", "province": "Merseyside", "postal_code": "WA10 3BW", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01546-942059", "phone2": "01244-769346", "email": "info@exhibitcraftsinc.co.uk", "web": "http://www.exhibitcraftsinc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
    }
}
