<?php

use Illuminate\Database\Seeder;

class QuotesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('quotes')->insert(['id' => 1, 'code' => 'QU200001', 'name' => 'Quote on 1 for customer 1 by contact 167', 'date' => '2020-01-01', 'due_date' => '2020-01-11', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Tax first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 167, 'customer_id' => 1, 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 2, 'code' => 'QU200002', 'name' => 'Quote on 2 for customer 2 by contact 135', 'date' => '2020-01-02', 'due_date' => '2020-01-12', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 135, 'customer_id' => 2, 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 3, 'code' => 'QU200003', 'name' => 'Quote on 3 for customer 3 by contact 6', 'date' => '2020-01-03', 'due_date' => '2020-01-13', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '10.00', 'contact_id' => 6, 'customer_id' => 3, 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 4, 'code' => 'QU200004', 'name' => 'Quote on 4 for customer 4 by contact 59', 'date' => '2020-01-04', 'due_date' => '2020-01-14', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 59, 'customer_id' => 4, 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 5, 'code' => 'QU200005', 'name' => 'Quote on 1 for customer 1 by contact 167', 'date' => '2020-02-01', 'due_date' => '2020-02-11', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '20.00', 'contact_id' => 167, 'customer_id' => 1, 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 6, 'code' => 'QU200006', 'name' => 'Quote on 2 for customer 2 by contact 135', 'date' => '2020-02-02', 'due_date' => '2020-02-12', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Discount first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 135, 'customer_id' => 2, 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 7, 'code' => 'QU200007', 'name' => 'Quote on 3 for customer 3 by contact 6', 'date' => '2020-02-03', 'due_date' => '2020-02-13', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '10.00', 'contact_id' => 6, 'customer_id' => 3, 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 8, 'code' => 'QU200008', 'name' => 'Quote on 4 for customer 4 by contact 59', 'date' => '2020-02-04', 'due_date' => '2020-02-14', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Discount first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 59, 'customer_id' => 4, 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 9, 'code' => 'QU200009', 'name' => 'Quote on 1 for customer 1 by contact 173', 'date' => '2020-03-01', 'due_date' => '2020-03-11', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 173, 'customer_id' => 1, 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 10, 'code' => 'QU200010', 'name' => 'Quote on 2 for customer 2 by contact 279', 'date' => '2020-03-02', 'due_date' => '2020-03-12', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '20.00', 'contact_id' => 279, 'customer_id' => 2, 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 11, 'code' => 'QU200011', 'name' => 'Quote on 3 for customer 3 by contact 81', 'date' => '2020-03-03', 'due_date' => '2020-03-13', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '10.00', 'contact_id' => 81, 'customer_id' => 3, 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 12, 'code' => 'QU200012', 'name' => 'Quote on 4 for customer 4 by contact 61', 'date' => '2020-03-04', 'due_date' => '2020-03-14', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 61, 'customer_id' => 4, 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 13, 'code' => 'QU200013', 'name' => 'Quote on 15 for customer 1 by contact 167', 'date' => '2020-03-15', 'due_date' => '2020-03-25', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Tax first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 167, 'customer_id' => 1, 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 14, 'code' => 'QU200014', 'name' => 'Quote on 16 for customer 2 by contact 135', 'date' => '2020-03-16', 'due_date' => '2020-03-26', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '10.00', 'contact_id' => 135, 'customer_id' => 2, 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 15, 'code' => 'QU200015', 'name' => 'Quote on 17 for customer 3 by contact 6', 'date' => '2020-03-17', 'due_date' => '2020-03-27', 'status' => 'Open', 'currency' => 'SEK', 'tdtype' => 'Lineal (Tax first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 6, 'customer_id' => 3, 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 16, 'code' => 'QU200016', 'name' => 'Quote on 18 for customer 4 by contact 59', 'date' => '2020-03-18', 'due_date' => '2020-03-28', 'status' => 'Open', 'currency' => 'SEK', 'tdtype' => 'Lineal (Discount first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 59, 'customer_id' => 4, 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 17, 'code' => 'QU200017', 'name' => 'Quote on 10 for customer 1 by contact 173', 'date' => '2020-04-10', 'due_date' => '2020-04-20', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 173, 'customer_id' => 1, 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 18, 'code' => 'QU200018', 'name' => 'Quote on 11 for customer 2 by contact 279', 'date' => '2020-04-11', 'due_date' => '2020-04-21', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Discount first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 279, 'customer_id' => 2, 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 19, 'code' => 'QU200019', 'name' => 'Quote on 12 for customer 3 by contact 81', 'date' => '2020-04-12', 'due_date' => '2020-04-22', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '20.00', 'contact_id' => 81, 'customer_id' => 3, 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 20, 'code' => 'QU200020', 'name' => 'Quote on 13 for customer 4 by contact 61', 'date' => '2020-04-13', 'due_date' => '2020-04-23', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Discount first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 61, 'customer_id' => 4, 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 21, 'code' => 'QU200021', 'name' => 'Quote on 17 for customer 1 by contact 173', 'date' => '2020-04-17', 'due_date' => '2020-04-27', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 173, 'customer_id' => 1, 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 22, 'code' => 'QU200022', 'name' => 'Quote on 18 for customer 2 by contact 279', 'date' => '2020-04-18', 'due_date' => '2020-04-28', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Discount first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 279, 'customer_id' => 2, 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 23, 'code' => 'QU200023', 'name' => 'Quote on 19 for customer 3 by contact 81', 'date' => '2020-04-19', 'due_date' => '2020-04-29', 'status' => 'Open', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '10.00', 'contact_id' => 81, 'customer_id' => 3, 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 24, 'code' => 'QU200024', 'name' => 'Quote on 20 for customer 4 by contact 61', 'date' => '2020-04-20', 'due_date' => '2020-04-30', 'status' => 'Open', 'currency' => '$', 'tdtype' => 'Lineal (Discount first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 61, 'customer_id' => 4, 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 25, 'code' => 'QU200025', 'name' => 'Quote on 1 for customer 1 by contact 167', 'date' => '2020-05-01', 'due_date' => '2020-05-11', 'status' => 'Closed', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 167, 'customer_id' => 1, 'address_info' => '{"address": "14 Taylor St", "city": "St. Stephens Ward", "province": "Kent", "postal_code": "CT2 7PP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01835-703597", "phone2": "01944-369967", "email": "info@alandrosenburgcpapc.co.uk", "web": "http://www.alandrosenburgcpapc.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 26, 'code' => 'QU200026', 'name' => 'Quote on 2 for customer 2 by contact 135', 'date' => '2020-05-02', 'due_date' => '2020-05-12', 'status' => 'Closed', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '20.00', 'contact_id' => 135, 'customer_id' => 2, 'address_info' => '{"address": "5 Binney St", "city": "Abbey Ward", "province": "Buckinghamshire", "postal_code": "HP11 2AX", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01937-864715", "phone2": "01714-737668", "email": "info@capgeminiamerica.co.uk", "web": "http://www.capgeminiamerica.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 27, 'code' => 'QU200027', 'name' => 'Quote on 3 for customer 3 by contact 6', 'date' => '2020-05-03', 'due_date' => '2020-05-13', 'status' => 'Closed', 'currency' => 'SEK', 'tdtype' => 'Lineal (Tax first)', 'tax' => '0', 'discount' => '0', 'contact_id' => 6, 'customer_id' => 3, 'address_info' => '{"address": "8 Moor Place", "city": "East Southbourne and Tuckton W", "province": "Bournemouth", "postal_code": "BH6 3BE", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01347-368222", "phone2": "01935-821636", "email": "info@elliottjohnwesq.co.uk", "web": "http://www.elliottjohnwesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 28, 'code' => 'QU200028', 'name' => 'Quote on 4 for customer 4 by contact 59', 'date' => '2020-05-04', 'due_date' => '2020-05-14', 'status' => 'Closed', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '20.00', 'contact_id' => 59, 'customer_id' => 4, 'address_info' => '{"address": "505 Exeter Rd", "city": "Hawerby cum Beesby", "province": "Lincolnshire", "postal_code": "DN36 5RP", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01912-771311", "phone2": "01302-601380", "email": "info@mcmahanbenl.co.uk", "web": "http://www.mcmahanbenl.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 29, 'code' => 'QU200029', 'name' => 'Quote on 5 for customer 5 by contact 106', 'date' => '2020-05-05', 'due_date' => '2020-05-15', 'status' => 'Closed', 'currency' => '€', 'tdtype' => 'General (Tax first)', 'tax' => '21.00', 'discount' => '15.00', 'contact_id' => 106, 'customer_id' => 5, 'address_info' => '{"address": "5396 Forth Street", "city": "Greets Green and Lyng Ward", "province": "West Midlands", "postal_code": "B70 9DT", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01547-429341", "phone2": "01290-367248", "email": "info@champagneroom.co.uk", "web": "http://www.champagneroom.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
            DB::table('quotes')->insert(['id' => 30, 'code' => 'QU200030', 'name' => 'Quote on 6 for customer 6 by contact 2', 'date' => '2020-05-06', 'due_date' => '2020-05-16', 'status' => 'Closed', 'currency' => '€', 'tdtype' => 'General (Discount first)', 'tax' => '21.00', 'discount' => '10.00', 'contact_id' => 2, 'customer_id' => 6, 'address_info' => '{"address": "9472 Lind St", "city": "Desborough", "province": "Northamptonshire", "postal_code": "NN14 2GH", "country": "United Kingdom"}', 'contact_info' => '{"phone1": "01969-886290", "phone2": "01545-817375", "email": "info@thompsonmichaelcesq.co.uk", "web": "http://www.thompsonmichaelcesq.co.uk"}', 'created_at' => date("Y-m-d H:i:s")]);
    }
}
